extension Nioh2 {

  static let soulCores: [SoulCore] = [
    SoulCore(name: "Gaki",                    type: .brute,   attunementCost:  4),
    SoulCore(name: "Enki",                    type: .brute,   attunementCost:  5),
    SoulCore(name: "Yoki",                    type: .brute,   attunementCost:  7),
    SoulCore(name: "Gozuki",                  type: .brute,   attunementCost:  9),
    SoulCore(name: "Mezuki",                  type: .brute,   attunementCost:  9),
    SoulCore(name: "Ippon-Datara",            type: .brute,   attunementCost:  7),
    SoulCore(name: "Kappa",                   type: .feral,   attunementCost:  4),
    SoulCore(name: "Nurikabe",                type: .brute,   attunementCost:  8),
    SoulCore(name: "Mujina",                  type: .phantom, attunementCost:  4),
    SoulCore(name: "Enenra",                  type: .phantom, attunementCost:  9),
    SoulCore(name: "Nure-Onna",               type: .feral,   attunementCost:  4),
    SoulCore(name: "Aberrant Soldier",        type: .brute,   attunementCost:  4),
    SoulCore(name: "Toxic Slime",             type: .phantom, attunementCost:  5),
    SoulCore(name: "Yatsu-no-Kami",           type: .phantom, attunementCost: 10),
    SoulCore(name: "Yamanba",                 type: .feral,   attunementCost:  6),
    SoulCore(name: "One-Eyed Oni",            type: .brute,   attunementCost:  7),
    SoulCore(name: "Karasu Tengu",            type: .feral,   attunementCost:  9),
    SoulCore(name: "Waira",                   type: .phantom, attunementCost:  8),
    SoulCore(name: "Karakasa Umbrella",       type: .feral,   attunementCost:  4),
    SoulCore(name: "Lesser Umi-bozu",         type: .phantom, attunementCost:  5),
    SoulCore(name: "Skeleton Warrior",        type: .phantom, attunementCost:  6),
    SoulCore(name: "Kamaitachi",              type: .feral,   attunementCost: 10),
    SoulCore(name: "Koroka",                  type: .phantom, attunementCost:  7),
    SoulCore(name: "Dweller",                 type: .feral,   attunementCost:  5),
    SoulCore(name: "Rokurokubi",              type: .phantom, attunementCost:  6),
    SoulCore(name: "Onryoki",                 type: .brute,   attunementCost:  8),
    SoulCore(name: "Mitsume Yazura",          type: .brute,   attunementCost:  7),
    SoulCore(name: "Biwa Boku-boku",          type: .phantom, attunementCost:  4),
    SoulCore(name: "Tatarimokke",             type: .phantom, attunementCost:  9),
    SoulCore(name: "Flying Bolt",             type: .phantom, attunementCost:  6),
    SoulCore(name: "Namahage",                type: .brute,   attunementCost:  7),
    SoulCore(name: "Tesso",                   type: .feral,   attunementCost:  5),
    SoulCore(name: "Ubume",                   type: .phantom, attunementCost:  4),
    SoulCore(name: "Onyudo",                  type: .brute,   attunementCost:  6),
    SoulCore(name: "Gyuki",                   type: .brute,   attunementCost: 10),
    SoulCore(name: "Wheelmonk",               type: .feral,   attunementCost:  4),
    SoulCore(name: "Kasha",                   type: .feral,   attunementCost: 10),
    SoulCore(name: "Ryomen Sukuna",           type: .brute,   attunementCost: 10),
    SoulCore(name: "Daidara Bocchi",          type: .brute,   attunementCost: 10),
    SoulCore(name: "Shuten Doji",             type: .brute,   attunementCost: 11),
    SoulCore(name: "Magatsu Warrior",         type: .brute,   attunementCost:  9),
    SoulCore(name: "Lady Osakabe",            type: .phantom, attunementCost: 10),
    SoulCore(name: "Otakemaru",               type: .phantom, attunementCost: 11),
    SoulCore(name: "Kodama",                  type: .phantom, attunementCost:  3),
    SoulCore(name: "Scampuss",                type: .feral,   attunementCost:  2),
    SoulCore(name: "Infernal Oni-bi",         type: .phantom, attunementCost:  4),
    SoulCore(name: "Maelstrom Oni-bi",        type: .phantom, attunementCost:  4),
    SoulCore(name: "Thunderstorm Oni-bi",     type: .phantom, attunementCost:  4),
    SoulCore(name: "Uminyudo",                type: .phantom, attunementCost: 10),
    SoulCore(name: "Seto Taisho",             type: .brute,   attunementCost:  5),
    SoulCore(name: "Bakegani",                type: .brute,   attunementCost:  5),
    SoulCore(name: "Kiryoki",                 type: .feral,   attunementCost:  6),
    SoulCore(name: "Nue",                     type: .phantom, attunementCost:  9),
    SoulCore(name: "Nuppeppo",                type: .feral,   attunementCost:  5),
    SoulCore(name: "Infernal Fox Spirit",     type: .phantom, attunementCost:  4),
    SoulCore(name: "Maelstrom Fox Spirit",    type: .phantom, attunementCost:  4),
    SoulCore(name: "Thunderstorm Fox Spirit", type: .phantom, attunementCost:  4),
    SoulCore(name: "Oboroguruma",             type: .feral,   attunementCost:  6),
    SoulCore(name: "Yasha",                   type: .feral,   attunementCost:  7),
    SoulCore(name: "Tsuchigumo",              type: .brute,   attunementCost:  8),
    SoulCore(name: "Giant Toad",              type: .phantom, attunementCost:  8),
    SoulCore(name: "Lightning Gods of Yomi",  type: .phantom, attunementCost:  9),
    SoulCore(name: "Hellish Hag",             type: .feral,   attunementCost:  6),
    SoulCore(name: "White Tiger",             type: .feral,   attunementCost:  8),
    SoulCore(name: "Underworld Soldier",      type: .brute,   attunementCost:  6),
    SoulCore(name: "Konaki-Jiji",             type: .brute,   attunementCost:  5),
    SoulCore(name: "Tate Eboshi",             type: .feral,   attunementCost:  9),
    SoulCore(name: "Fuki",                    type: .feral,   attunementCost:  6),
    SoulCore(name: "Harinobo",                type: .brute,   attunementCost:  5),
    SoulCore(name: "Itsumade",                type: .phantom, attunementCost:  7),
    SoulCore(name: "Kinki",                   type: .brute,   attunementCost:  6),
    SoulCore(name: "Ancient Nyotengu",        type: .feral,   attunementCost:  8),
    SoulCore(name: "Ongyoki",                 type: .phantom, attunementCost:  6),
    SoulCore(name: "Suiki",                   type: .phantom, attunementCost:  6),
    SoulCore(name: "Nightmare Bringer",       type: .brute,   attunementCost: 10),
  ]

}

extension Nioh2 {

  static let guardianSpirits: [GuardianSpirit] = [
    GuardianSpirit(name: "Makami",           element: .fire,       type: .brute,   attunementLimit: 20),
    GuardianSpirit(name: "Ame-no-Mitori",    element: .lightning,  type: .feral,   attunementLimit: 21),
    GuardianSpirit(name: "Kagewani",         element: .water,      type: .phantom, attunementLimit: 24),
    GuardianSpirit(name: "Okuri-Inu",        element: .fire,       type: .brute,   attunementLimit: 22),
    GuardianSpirit(name: "Masaru",           element: .fire,       type: .feral,   attunementLimit: 23),
    GuardianSpirit(name: "Shirohami",        element: .water,      type: .brute,   attunementLimit: 21),
    GuardianSpirit(name: "Hyobishin",        element: .fire,       type: .brute,   attunementLimit: 24),
    GuardianSpirit(name: "Nekomata",         element: .lightning,  type: .feral,   attunementLimit: 22),
    GuardianSpirit(name: "Yaonami-Hime",     element: .water,      type: .feral,   attunementLimit: 23),
    GuardianSpirit(name: "Rokugezo",         element: .lightning,  type: .phantom, attunementLimit: 23),
    GuardianSpirit(name: "Usura-Hicho",      element: .water,      type: .phantom, attunementLimit: 20),
    GuardianSpirit(name: "Shin-Roku",        element: .lightning,  type: .brute,   attunementLimit: 24),
    GuardianSpirit(name: "Hiyokucho",        element: .water,      type: .feral,   attunementLimit: 22),
    GuardianSpirit(name: "Tengen Kujaku",    element: .fire,       type: .phantom, attunementLimit: 24),
    GuardianSpirit(name: "Nine Tails",       element: .fire,       type: .phantom, attunementLimit: 23),
    GuardianSpirit(name: "Atlas Bear",       element: .lightning,  type: .brute,   attunementLimit: 20),
    GuardianSpirit(name: "Genbu",            element: .water,      type: .phantom, attunementLimit: 24),
    GuardianSpirit(name: "Gyokuto",          element: .lightning,  type: .feral,   attunementLimit: 20),
    GuardianSpirit(name: "Saoirse",          element: .water,      type: .phantom, attunementLimit: 20),
    GuardianSpirit(name: "Yumehami",         element: .lightning,  type: .phantom, attunementLimit: 21),
    GuardianSpirit(name: "Isanagami",        element: .water,      type: .brute,   attunementLimit: 24),
    GuardianSpirit(name: "Hakutaku",         element: .lightning,  type: .phantom, attunementLimit: 23),
    GuardianSpirit(name: "Inosasao",         element: .fire,       type: .brute,   attunementLimit: 21),
    GuardianSpirit(name: "Yatagarasu",       element: .fire,       type: .feral,   attunementLimit: 22),
    GuardianSpirit(name: "Itokuri",          element: .water,      type: .feral,   attunementLimit: 22),
    GuardianSpirit(name: "Mizuchi",          element: .water,      type: .brute,   attunementLimit: 20),
    GuardianSpirit(name: "Blue Dragon",      element: .lightning,  type: .phantom, attunementLimit: 24),
    GuardianSpirit(name: "Suzaku",           element: .fire,       type: .phantom, attunementLimit: 24),
    GuardianSpirit(name: "Kurama Tengu",     element: .purity,     type: .feral,   attunementLimit: 22),
    GuardianSpirit(name: "Sohaya",           element: .purity,     type: .feral,   attunementLimit: 26),
    GuardianSpirit(name: "Amiabe",           element: .purity,     type: .phantom, attunementLimit: 23),
    GuardianSpirit(name: "Ho",               element: .purity,     type: .brute,   attunementLimit: 25),
    GuardianSpirit(name: "Oh",               element: .purity,     type: .feral,   attunementLimit: 25),
    GuardianSpirit(name: "Ho-oh",            element: .purity,     type: .phantom, attunementLimit: 26),
    GuardianSpirit(name: "Janomecho",        element: .corruption, type: .feral,   attunementLimit: 22),
    GuardianSpirit(name: "Kuzunoha the Fox", element: .corruption, type: .phantom, attunementLimit: 24),
    GuardianSpirit(name: "Baku",             element: .corruption, type: .brute,   attunementLimit: 26),
  ]

}

extension Nioh2 {

  static let bosses: [Boss] = [
    Boss(name: "Ancient Nyotengu"),
    Boss(name: "Ashiya Doman"),
    Boss(name: "Azai Nagamasa"),
    Boss(name: "Benkei"),
    Boss(name: "Daidara Bocchi"),
    Boss(name: "Enenra"),
    Boss(name: "Giant Toad"),
    Boss(name: "Gozuki"),
    Boss(name: "Gyuki"),
    Boss(name: "Hachisuka Koroku"),
    Boss(name: "Honda Tadakatsu"),
    Boss(name: "Imagawa Yoshimoto"),
    Boss(name: "Kamaitachi"),
    Boss(name: "Kasha"),
    Boss(name: "Kashin Koji"),
    Boss(name: "Lady Osakabe"),
    Boss(name: "Lightning Gods of Yomi"),
    Boss(name: "Maeda Toshiie"),
    Boss(name: "Magara Naotaka"),
    Boss(name: "Matsunaga Hisahide"),
    Boss(name: "Mezuki"),
    Boss(name: "Nightmare Bringer"),
    Boss(name: "Nue"),
    Boss(name: "Obsidian Samurai"),
    Boss(name: "Oda Nobunaga"),
    Boss(name: "Onryoki"),
    Boss(name: "Otakemaru (Afterglow)"),
    Boss(name: "Ren Hayabusa"),
    Boss(name: "Ryomen Sukuna"),
    Boss(name: "Saika Magoichi"),
    Boss(name: "Saito Toshimitsu"),
    Boss(name: "Saito Yoshitatsu"),
    Boss(name: "Shibata Katsuie"),
    Boss(name: "Shuten Doji"),
    Boss(name: "Tatarimokke"),
    Boss(name: "Tate Eboshi"),
    Boss(name: "Tokichiro (Dream)"),
    Boss(name: "Tokichiro (Twilight)"),
    Boss(name: "Tsuchigumo"),
    Boss(name: "Uminyudo"),
    Boss(name: "White Tiger"),
    Boss(name: "William"),
    Boss(name: "Yatsu-no-Kami"),
    Boss(name: "Minamoto no Yorimitsu"),
    Boss(name: "Minamoto no Yoshitsune"),
  ]

  static let floorLayouts: [FloorLayout] = [
    FloorLayout(name: "Anegawa",                                    scampuss: 2, smallSudama: 0, largeSudama: 0, darkRealms: 1, majorEnemies: 4, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "Bathhouse",                                  scampuss: 3, smallSudama: 0, largeSudama: 0, darkRealms: 2, majorEnemies: 3, bigChests: 2, hotSprings: 7),
    FloorLayout(name: "Burial Temple",                              scampuss: 1, smallSudama: 2, largeSudama: 0, darkRealms: 2, majorEnemies: 4, bigChests: 1, hotSprings: 0),
    FloorLayout(name: "Byodo-in",                                   scampuss: 3, smallSudama: 1, largeSudama: 1, darkRealms: 2, majorEnemies: 8, bigChests: 4, hotSprings: 0),
    FloorLayout(name: "Daigo Temple",                               scampuss: 3, smallSudama: 0, largeSudama: 0, darkRealms: 0, majorEnemies: 2, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "Forest",                                     scampuss: 2, smallSudama: 0, largeSudama: 0, darkRealms: 0, majorEnemies: 3, bigChests: 0, hotSprings: 0),
    FloorLayout(name: "Heian Palace",                               scampuss: 2, smallSudama: 1, largeSudama: 0, darkRealms: 1, majorEnemies: 5, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "Honnoji",                                    scampuss: 2, smallSudama: 0, largeSudama: 1, darkRealms: 2, majorEnemies: 5, bigChests: 5, hotSprings: 0),
    FloorLayout(name: "Inabayama Castle",                           scampuss: 2, smallSudama: 1, largeSudama: 0, darkRealms: 1, majorEnemies: 6, bigChests: 3, hotSprings: 1),
    FloorLayout(name: "Ishiyama Honganji",                          scampuss: 2, smallSudama: 1, largeSudama: 0, darkRealms: 0, majorEnemies: 4, bigChests: 1, hotSprings: 0),
    FloorLayout(name: "Island",                                     scampuss: 1, smallSudama: 0, largeSudama: 1, darkRealms: 3, majorEnemies: 3, bigChests: 2, hotSprings: 1),
    FloorLayout(name: "Jurakudai",                                  scampuss: 3, smallSudama: 0, largeSudama: 0, darkRealms: 0, majorEnemies: 2, bigChests: 2, hotSprings: 1),
    FloorLayout(name: "Jusanzakura",                                scampuss: 2, smallSudama: 0, largeSudama: 1, darkRealms: 1, majorEnemies: 2, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "Kanegasaki",                                 scampuss: 1, smallSudama: 0, largeSudama: 0, darkRealms: 1, majorEnemies: 5, bigChests: 3, hotSprings: 1),
    FloorLayout(name: "Kitanosho Castle",                           scampuss: 3, smallSudama: 0, largeSudama: 3, darkRealms: 2, majorEnemies: 5, bigChests: 5, hotSprings: 1),
    FloorLayout(name: "Komaki-Nagakute (The High-Spirited Demon)",  scampuss: 2, smallSudama: 1, largeSudama: 0, darkRealms: 1, majorEnemies: 6, bigChests: 4, hotSprings: 1),
    FloorLayout(name: "Komaki-Nagakute (Two Faces of Hospitality)", scampuss: 2, smallSudama: 0, largeSudama: 1, darkRealms: 3, majorEnemies: 1, bigChests: 4, hotSprings: 0),
    FloorLayout(name: "Kurama",                                     scampuss: 1, smallSudama: 1, largeSudama: 0, darkRealms: 1, majorEnemies: 6, bigChests: 4, hotSprings: 0),
    FloorLayout(name: "Mount Ibuki",                                scampuss: 2, smallSudama: 0, largeSudama: 1, darkRealms: 1, majorEnemies: 4, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "Mount Tenno",                                scampuss: 1, smallSudama: 0, largeSudama: 0, darkRealms: 0, majorEnemies: 5, bigChests: 2, hotSprings: 0),
    FloorLayout(name: "Mountain Temple",                            scampuss: 3, smallSudama: 0, largeSudama: 1, darkRealms: 0, majorEnemies: 5, bigChests: 4, hotSprings: 0),
    FloorLayout(name: "Nanbanji",                                   scampuss: 1, smallSudama: 0, largeSudama: 0, darkRealms: 1, majorEnemies: 3, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "Odani Castle",                               scampuss: 2, smallSudama: 0, largeSudama: 0, darkRealms: 1, majorEnemies: 6, bigChests: 3, hotSprings: 1),
    FloorLayout(name: "Okehazama",                                  scampuss: 3, smallSudama: 0, largeSudama: 3, darkRealms: 2, majorEnemies: 5, bigChests: 6, hotSprings: 0),
    FloorLayout(name: "Oniga Castle",                   scampuss: nil, smallSudama: nil, largeSudama: nil, darkRealms: nil, majorEnemies: nil, bigChests: nil, hotSprings: nil),
    FloorLayout(name: "Pagoda",                         scampuss: nil, smallSudama: nil, largeSudama: nil, darkRealms: nil, majorEnemies: nil, bigChests: nil, hotSprings: nil),
    FloorLayout(name: "Rashomon",                                   scampuss: 1, smallSudama: 0, largeSudama: 1, darkRealms: 1, majorEnemies: 8, bigChests: 4, hotSprings: 0),
    FloorLayout(name: "Shigisan Castle",                            scampuss: 2, smallSudama: 0, largeSudama: 2, darkRealms: 3, majorEnemies: 4, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "Spirit Stone Mine",                          scampuss: 2, smallSudama: 2, largeSudama: 0, darkRealms: 1, majorEnemies: 3, bigChests: 3, hotSprings: 1),
    FloorLayout(name: "Sunomata",                                   scampuss: 2, smallSudama: 0, largeSudama: 1, darkRealms: 1, majorEnemies: 3, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "Suzuka Pass",                                scampuss: 1, smallSudama: 0, largeSudama: 0, darkRealms: 1, majorEnemies: 5, bigChests: 2, hotSprings: 1),
    FloorLayout(name: "Tatara",                                     scampuss: 1, smallSudama: 1, largeSudama: 0, darkRealms: 1, majorEnemies: 6, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "The Viper's Sanctum",                        scampuss: 2, smallSudama: 0, largeSudama: 1, darkRealms: 1, majorEnemies: 5, bigChests: 3, hotSprings: 1),
    FloorLayout(name: "Todai-ji Temple",                            scampuss: 1, smallSudama: 0, largeSudama: 0, darkRealms: 1, majorEnemies: 4, bigChests: 3, hotSprings: 0),
    FloorLayout(name: "Volcano Temple",                             scampuss: 2, smallSudama: 0, largeSudama: 1, darkRealms: 1, majorEnemies: 5, bigChests: 4, hotSprings: 0),
    FloorLayout(name: "Yashima",                                    scampuss: 0, smallSudama: 0, largeSudama: 0, darkRealms: 0, majorEnemies: 6, bigChests: 4, hotSprings: 0),
  ]

  static let underworldFloors: [UnderworldFloor] = loadUnderworld(floors: [
    (layout: "Kurama",                                     boss: "Mezuki"),
    (layout: "Spirit Stone Mine",                          boss: "Honda Tadakatsu"),
    (layout: "Komaki-Nagakute (Two Faces of Hospitality)", boss: "Tatarimokke"),
    (layout: "Kanegasaki",                                 boss: "Magara Naotaka"),
    (layout: "Sunomata",                                   boss: "Imagawa Yoshimoto"),
    (layout: "Volcano Temple",                             boss: "Shibata Katsuie"),
    (layout: "Ishiyama Honganji",                          boss: "Obsidian Samurai"),
    (layout: "Forest",                                     boss: "Onryoki"),
    (layout: "Odani Castle",                               boss: "Saito Toshimitsu"),
    (layout: "Anegawa",                                    boss: "Kashin Koji"),
    (layout: "Nanbanji",                                   boss: "Ryomen Sukuna"),
    (layout: "Mount Tenno",                                boss: "Hachisuka Koroku"),
    (layout: "Daigo Temple",                               boss: "Kamaitachi"),
    (layout: "Byodo-in",                                   boss: "Azai Nagamasa"),
    (layout: "Komaki-Nagakute (The High-Spirited Demon)",  boss: "Oda Nobunaga"),
    (layout: "The Viper's Sanctum",                        boss: "Shuten Doji"),
    (layout: "Tatara",                                     boss: "Maeda Toshiie"),
    (layout: "Kitanosho Castle",                           boss: "Yatsu-no-Kami"),
    (layout: "Yashima",                                    boss: "William"),
    (layout: "Inabayama Castle",                           boss: "Tokichiro (Dream)"),
    (layout: "Volcano Temple",                             boss: "Kasha"),
    (layout: "Heian Palace",                               boss: "Saito Yoshitatsu"),
    (layout: "Shigisan Castle",                            boss: "Magara Naotaka"),
    (layout: "Jusanzakura",                                boss: "Matsunaga Hisahide"),
    (layout: "Forest",                                     boss: "Enenra"),
    (layout: "Burial Temple",                              boss: "Saika Magoichi"),
    (layout: "Honnoji",                                    boss: "Gozuki"),
    (layout: "Kanegasaki",                                 boss: "Hachisuka Koroku"),
    (layout: "Island",                                     boss: "Tokichiro (Twilight)"),
    (layout: "Jurakudai",                                  boss: "Otakemaru (Afterglow)"),
    (layout: "Todai-ji Temple",                            boss: "Tsuchigumo"),
    (layout: "Okehazama",                                  boss: "Saito Toshimitsu"),
    (layout: "Bathhouse",                                  boss: "Giant Toad"),
    (layout: "Mountain Temple",                            boss: "Maeda Toshiie"),
    (layout: "Mount Ibuki",                                boss: "Kasha"),
    (layout: "Rashomon",                                   boss: "Tokichiro (Dream)"),
    (layout: "Odani Castle",                               boss: "Nue"),
    (layout: "Volcano Temple",                             boss: "Oda Nobunaga"),
    (layout: "Tatara",                                     boss: "Benkei"),
    (layout: "Okehazama",                                  boss: "White Tiger"),
    (layout: "Spirit Stone Mine",                          boss: "Ashiya Doman"),
    (layout: "Rashomon",                                   boss: "Shibata Katsuie"),
    (layout: "Heian Palace",                               boss: "Honda Tadakatsu"),
    (layout: "Forest",                                     boss: "Tsuchigumo"),
    (layout: "Jusanzakura",                                boss: "Kashin Koji"),
    (layout: "Shigisan Castle",                            boss: "Lightning Gods of Yomi"),
    (layout: "Daigo Temple",                               boss: "Imagawa Yoshimoto"),
    (layout: "Ishiyama Honganji",                          boss: "Minamoto no Yoshitsune"),
    (layout: "Kitanosho Castle",                           boss: "Minamoto no Yorimitsu"),
    (layout: "Komaki-Nagakute (Two Faces of Hospitality)", boss: "Nightmare Bringer"),
    (layout: "Todai-ji Temple",                            boss: "Onryoki"),
    (layout: "Byodo-in",                                   boss: "Ancient Nyotengu"),
    (layout: "Mount Tenno",                                boss: "Nue"),
    (layout: "The Viper's Sanctum",                        boss: "Saito Yoshitatsu"),
    (layout: "Honnoji",                                    boss: "Yatsu-no-Kami"),
    (layout: "Bathhouse",                                  boss: "Ryomen Sukuna"),
    (layout: "Mount Ibuki",                                boss: "Matsunaga Hisahide"),
    (layout: "Kanegasaki",                                 boss: "Magara Naotaka"),
    (layout: "Yashima",                                    boss: "White Tiger"),
    (layout: "Komaki-Nagakute (The High-Spirited Demon)",  boss: "Giant Toad"),
    (layout: "Inabayama Castle",                           boss: "Tate Eboshi"),
    (layout: "Burial Temple",                              boss: "Honda Tadakatsu"),
    (layout: "Nanbanji",                                   boss: "Saika Magoichi"),
    (layout: "Spirit Stone Mine",                          boss: "Azai Nagamasa"),
    (layout: "Island",                                     boss: "Maeda Toshiie"),
    (layout: "Kurama",                                     boss: "Lightning Gods of Yomi"),
    (layout: "Anegawa",                                    boss: "Kamaitachi"),
    (layout: "Kitanosho Castle",                           boss: "Obsidian Samurai"),
    (layout: "Jurakudai",                                  boss: "Oda Nobunaga"),
    (layout: "Mountain Temple",                            boss: "William"),
    (layout: "Sunomata",                                   boss: "Enenra"),
    (layout: "Todai-ji Temple",                            boss: "Minamoto no Yoshitsune"),
    (layout: "Yashima",                                    boss: "Tatarimokke"),
    (layout: "Nanbanji",                                   boss: "Shuten Doji"),
    (layout: "Okehazama",                                  boss: "Tokichiro (Twilight)"),
    (layout: "Komaki-Nagakute (The High-Spirited Demon)",  boss: "Tsuchigumo"),
    (layout: "Bathhouse",                                  boss: "Ren Hayabusa"),
    (layout: "Mount Ibuki",                                boss: "Ryomen Sukuna"),
    (layout: "Jurakudai",                                  boss: "Kasha"),
    (layout: "Forest",                                     boss: "Minamoto no Yorimitsu"),
    (layout: "Tatara",                                     boss: "Ancient Nyotengu"),
    (layout: "Anegawa",                                    boss: "Tate Eboshi"),
    (layout: "Volcano Temple",                             boss: "Saito Toshimitsu"),
    (layout: "Mount Tenno",                                boss: "Benkei"),
    (layout: "Jusanzakura",                                boss: "Imagawa Yoshimoto"),
    (layout: "Mountain Temple",                            boss: "Shibata Katsuie"),
    (layout: "Heian Palace",                               boss: "Hachisuka Koroku"),
    (layout: "Odani Castle",                               boss: "Gozuki"),
    (layout: "Kanegasaki",                                 boss: "Saika Magoichi"),
    (layout: "Daigo Temple",                               boss: "William"),
    (layout: "Sunomata",                                   boss: "Lightning Gods of Yomi"),
    (layout: "Spirit Stone Mine",                          boss: "Saito Yoshitatsu"),
    (layout: "Rashomon",                                   boss: "Giant Toad"),
    (layout: "Honnoji",                                    boss: "Matsunaga Hisahide"),
    (layout: "Anegawa",                                    boss: "Minamoto no Yoshitsune"),
    (layout: "Inabayama Castle",                           boss: "Kamaitachi"),
    (layout: "Ishiyama Honganji",                          boss: "Obsidian Samurai"),
    (layout: "The Viper's Sanctum",                        boss: "Mezuki"),
    (layout: "Kurama",                                     boss: "Nue"),
    (layout: "Mountain Temple",                            boss: "Ren Hayabusa"),
    (layout: "Island",                                     boss: "Ancient Nyotengu"),
    (layout: "Todai-ji Temple",                            boss: "White Tiger"),
    (layout: "Burial Temple",                              boss: "Azai Nagamasa"),
    (layout: "Kitanosho Castle",                           boss: "Tokichiro (Dream)"),
    (layout: "Komaki-Nagakute (Two Faces of Hospitality)", boss: "Ashiya Doman"),
    (layout: "Shigisan Castle",                            boss: "Kashin Koji"),
    (layout: "Byodo-in",                                   boss: "Otakemaru (Afterglow)"),
    (layout: "Daigo Temple",                               boss: "Nightmare Bringer"),
  ], bosses: bosses, floorLayouts: floorLayouts)

  static fileprivate func loadUnderworld(floors: [(layout: String, boss: String)], bosses: [Boss], floorLayouts: [FloorLayout]) -> [UnderworldFloor] {
    let floorLayouts: [String: FloorLayout] = floorLayouts
      .reduce(into: [:]) { dict, floorLayout in
        dict[floorLayout.name] = floorLayout
      }

    let bosses: [String: Boss] = bosses
      .reduce(into: [:]) { dict, boss in
        dict[boss.name] = boss
      }

    return zip(1...floors.count, floors)
      .map { floorNumber, floor in
        UnderworldFloor(floorNumber: floorNumber, floorLayout: floorLayouts[floor.layout]!, boss: bosses[floor.boss]!)
      }
  }
}

extension Nioh2 {

  static let weapons: [Weapon] = [
    Weapon(type: "Sword", variants: ["Uchigatana","Tachi"]),
    Weapon(type: "Dual Swords"),
    Weapon(type: "Odachi"),
    Weapon(type: "Axe", variants: ["Axe","Hammer"]),
    Weapon(type: "Spear", variants: ["Spear","Cross Spear"]),
    Weapon(type: "Kusarigama"),
    Weapon(type: "Tonfa"),
    Weapon(type: "Hatchets"),
    Weapon(type: "Switchglaive"),
    Weapon(type: "Fists", variants: ["Fists","Claws"]),
    Weapon(type: "Splitstaff"),
  ]

}

extension Nioh2 {

  static let regions: [Region] = [
    Region(name: "Awakening",               startYear: 1555, endYear: 1556, isDLC: false),
    Region(name: "Soaring",                 startYear: 1560, endYear: 1567, isDLC: false),
    Region(name: "Shadow",                  startYear: 1570, endYear: 1573, isDLC: false),
    Region(name: "Dawn",                    startYear: 1578, endYear: 1582, isDLC: false),
    Region(name: "Twilight",                startYear: 1583, endYear: 1584, isDLC: false),
    Region(name: "Dream",                   startYear: 1590, endYear: 1598, isDLC: false),
    Region(name: "Afterglow",               startYear:  nil, endYear: 1616, isDLC: false),

    Region(name: "The Tengu's Disciple",    startYear: 1185, endYear:  nil, isDLC:  true),
    Region(name: "Darkness in the Capital", startYear:  976, endYear:  nil, isDLC:  true),
    Region(name: "The First Samurai",       startYear:  797, endYear:  nil, isDLC:  true),
  ]

}
