extension Nioh2 {

  static let soulCores: [SoulCore] = [
    SoulCore(name: "Gaki",                    type: .brute,   attunementCost:  4),
    SoulCore(name: "Enki",                    type: .brute,   attunementCost:  5),
    SoulCore(name: "Yoki",                    type: .brute,   attunementCost:  7),
    SoulCore(name: "Gozuki",                  type: .brute,   attunementCost:  9),
    SoulCore(name: "Mezuki",                  type: .brute,   attunementCost:  9),
    SoulCore(name: "Ippon-Datara",            type: .brute,   attunementCost:  7),
    SoulCore(name: "Kappa",                   type: .feral,   attunementCost:  4),
    SoulCore(name: "Nurikabe",                type: .brute,   attunementCost:  8),
    SoulCore(name: "Mujina",                  type: .phantom, attunementCost:  4),
    SoulCore(name: "Enenra",                  type: .phantom, attunementCost:  9),
    SoulCore(name: "Nure-Onna",               type: .feral,   attunementCost:  4),
    SoulCore(name: "Aberrant Soldier",        type: .brute,   attunementCost:  4),
    SoulCore(name: "Toxic Slime",             type: .phantom, attunementCost:  5),
    SoulCore(name: "Yatsu-no-Kami",           type: .phantom, attunementCost: 10),
    SoulCore(name: "Yamanba",                 type: .feral,   attunementCost:  6),
    SoulCore(name: "One-Eyed Oni",            type: .brute,   attunementCost:  7),
    SoulCore(name: "Karasu Tengu",            type: .feral,   attunementCost:  9),
    SoulCore(name: "Waira",                   type: .phantom, attunementCost:  8),
    SoulCore(name: "Karakasa Umbrella",       type: .feral,   attunementCost:  4),
    SoulCore(name: "Lesser Umi-bozu",         type: .phantom, attunementCost:  5),
    SoulCore(name: "Skeleton Warrior",        type: .phantom, attunementCost:  6),
    SoulCore(name: "Kamaitachi",              type: .feral,   attunementCost: 10),
    SoulCore(name: "Koroka",                  type: .phantom, attunementCost:  7),
    SoulCore(name: "Dweller",                 type: .feral,   attunementCost:  5),
    SoulCore(name: "Rokurokubi",              type: .phantom, attunementCost:  6),
    SoulCore(name: "Onryoki",                 type: .brute,   attunementCost:  8),
    SoulCore(name: "Mitsume Yazura",          type: .brute,   attunementCost:  7),
    SoulCore(name: "Biwa Boku-boku",          type: .phantom, attunementCost:  4),
    SoulCore(name: "Tatarimokke",             type: .phantom, attunementCost:  9),
    SoulCore(name: "Flying Bolt",             type: .phantom, attunementCost:  6),
    SoulCore(name: "Namahage",                type: .brute,   attunementCost:  7),
    SoulCore(name: "Tesso",                   type: .feral,   attunementCost:  5),
    SoulCore(name: "Ubume",                   type: .phantom, attunementCost:  4),
    SoulCore(name: "Onyudo",                  type: .brute,   attunementCost:  6),
    SoulCore(name: "Gyuki",                   type: .brute,   attunementCost: 10),
    SoulCore(name: "Wheelmonk",               type: .feral,   attunementCost:  4),
    SoulCore(name: "Kasha",                   type: .feral,   attunementCost: 10),
    SoulCore(name: "Ryomen Sukuna",           type: .brute,   attunementCost: 10),
    SoulCore(name: "Daidara Bocchi",          type: .brute,   attunementCost: 10),
    SoulCore(name: "Shuten Doji",             type: .brute,   attunementCost: 11),
    SoulCore(name: "Magatsu Warrior",         type: .brute,   attunementCost:  9),
    SoulCore(name: "Lady Osakabe",            type: .phantom, attunementCost: 10),
    SoulCore(name: "Otakemaru",               type: .phantom, attunementCost: 11),
    SoulCore(name: "Kodama",                  type: .phantom, attunementCost:  3),
    SoulCore(name: "Scampuss",                type: .feral,   attunementCost:  2),
    SoulCore(name: "Infernal Oni-bi",         type: .phantom, attunementCost:  4),
    SoulCore(name: "Maelstrom Oni-bi",        type: .phantom, attunementCost:  4),
    SoulCore(name: "Thunderstorm Oni-bi",     type: .phantom, attunementCost:  4),
    SoulCore(name: "Uminyudo",                type: .phantom, attunementCost: 10),
    SoulCore(name: "Seto Taisho",             type: .brute,   attunementCost:  5),
    SoulCore(name: "Bakegani",                type: .brute,   attunementCost:  5),
    SoulCore(name: "Kiryoki",                 type: .feral,   attunementCost:  6),
    SoulCore(name: "Nue",                     type: .phantom, attunementCost:  9),
    SoulCore(name: "Nuppeppo",                type: .feral,   attunementCost:  5),
    SoulCore(name: "Infernal Fox Spirit",     type: .phantom, attunementCost:  4),
    SoulCore(name: "Maelstrom Fox Spirit",    type: .phantom, attunementCost:  4),
    SoulCore(name: "Thunderstorm Fox Spirit", type: .phantom, attunementCost:  4),
    SoulCore(name: "Oboroguruma",             type: .feral,   attunementCost:  6),
    SoulCore(name: "Yasha",                   type: .feral,   attunementCost:  7),
    SoulCore(name: "Tsuchigumo",              type: .brute,   attunementCost:  8),
    SoulCore(name: "Giant Toad",              type: .phantom, attunementCost:  8),
    SoulCore(name: "Lightning Gods of Yomi",  type: .phantom, attunementCost:  9),
    SoulCore(name: "Hellish Hag",             type: .feral,   attunementCost:  6),
    SoulCore(name: "White Tiger",             type: .feral,   attunementCost:  8),
    SoulCore(name: "Underworld Soldier",      type: .brute,   attunementCost:  6),
    SoulCore(name: "Konaki-Jiji",             type: .brute,   attunementCost:  5),
    SoulCore(name: "Tate Eboshi",             type: .feral,   attunementCost:  9),
    SoulCore(name: "Fuki",                    type: .feral,   attunementCost:  6),
    SoulCore(name: "Harinobo",                type: .brute,   attunementCost:  5),
    SoulCore(name: "Itsumade",                type: .phantom, attunementCost:  7),
    SoulCore(name: "Kinki",                   type: .brute,   attunementCost:  6),
    SoulCore(name: "Ancient Nyotengu",        type: .feral,   attunementCost:  8),
    SoulCore(name: "Ongyoki",                 type: .phantom, attunementCost:  6),
    SoulCore(name: "Suiki",                   type: .phantom, attunementCost:  6),
    SoulCore(name: "Nightmare Bringer",       type: .brute,   attunementCost: 10),
  ]

}

extension Nioh2 {

  static let weapons: [Weapon] = [
    Weapon(type: "Sword", variants: ["Uchigatana","Tachi"]),
    Weapon(type: "Dual Swords"),
    Weapon(type: "Odachi"),
    Weapon(type: "Axe", variants: ["Axe","Hammer"]),
    Weapon(type: "Spear", variants: ["Spear","Cross Spear"]),
    Weapon(type: "Kusarigama"),
    Weapon(type: "Tonfa"),
    Weapon(type: "Hatchets"),
    Weapon(type: "Switchglaive"),
    Weapon(type: "Fists", variants: ["Fists","Claws"]),
    Weapon(type: "Splitstaff"),
  ]

}
